-- ============================================================================
-- scan_delta_reports
-- ============================================================================
--
-- Per-user visual delta between two body scans, scored 1-10 by Gemini.
-- Generated by ScanComparisonService after a rescan completes (~30 days
-- after the onboarding scan). Surfaces in the coach's PT context so the
-- coach can reference real visible progress on every message.
--
-- Score columns are flat (shoulders_before / shoulders_after, …) for
-- queryability. The Swift `ScanDeltaReport` model uses nested
-- `BodyPartDelta` structs in-memory; `ScanDeltaReportRow` is the flat
-- Codable shape used only for this upsert.

create table public.scan_delta_reports (
    id uuid primary key default gen_random_uuid(),
    user_id uuid not null references public.users(id) on delete cascade,
    baseline_scan_id uuid references public.scans(id) on delete set null,
    comparison_scan_id uuid references public.scans(id) on delete set null,
    created_at timestamptz not null default now(),

    shoulders_before int,
    shoulders_after  int,
    chest_before     int,
    chest_after      int,
    arms_before      int,
    arms_after       int,
    core_before      int,
    core_after       int,
    legs_before      int,
    legs_after       int,
    overall_before   int,
    overall_after    int,

    narrative         text,
    improvements      jsonb not null default '[]'::jsonb,
    lagging_areas     jsonb not null default '[]'::jsonb,
    recommended_focus text
);

create index scan_delta_reports_user_idx
    on public.scan_delta_reports (user_id, created_at desc);

alter table public.scan_delta_reports enable row level security;

create policy "scan_delta_reports_owner" on public.scan_delta_reports
    for all
    using (user_id = auth.uid())
    with check (user_id = auth.uid());

-- ============================================================================
-- END scan_delta_reports
-- ============================================================================
